#!/bin/bash
cd .. && go build . && mv protoc-gen-error ~/go/bin/
protoc -I=. --go_out=paths=source_relative:./pb/ --error_out=paths=source_relative:./pb/ --proto_path=./testdata/proto \
testdata/proto/test.proto


