// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.17.3
// source: testdata/test.proto

package test

import (
	reflect "reflect"
	sync "sync"

	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Status int32

const (
	Status_Status_Default Status = 0
	Status_Status_Success Status = 1
	Status_Status_Failure Status = 2
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "Status_Default",
		1: "Status_Success",
		2: "Status_Failure",
	}
	Status_value = map[string]int32{
		"Status_Default": 0,
		"Status_Success": 1,
		"Status_Failure": 2,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_testdata_test_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_testdata_test_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_testdata_test_proto_rawDescGZIP(), []int{0}
}

type Outer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OuterString string `protobuf:"bytes,1,opt,name=outer_string,json=outerString,proto3" json:"outer_string,omitempty"`
	Inner       *Inner `protobuf:"bytes,2,opt,name=inner,proto3" json:"inner,omitempty"`
	Status      Status `protobuf:"varint,3,opt,name=status,proto3,enum=test.Status" json:"status,omitempty"`
}

func (x *Outer) Reset() {
	*x = Outer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testdata_test_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Outer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Outer) ProtoMessage() {}

func (x *Outer) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_test_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Outer.ProtoReflect.Descriptor instead.
func (*Outer) Descriptor() ([]byte, []int) {
	return file_testdata_test_proto_rawDescGZIP(), []int{0}
}

func (x *Outer) GetOuterString() string {
	if x != nil {
		return x.OuterString
	}
	return ""
}

func (x *Outer) GetInner() *Inner {
	if x != nil {
		return x.Inner
	}
	return nil
}

func (x *Outer) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_Status_Default
}

type Inner struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InnerString        string    `protobuf:"bytes,1,opt,name=inner_string,json=innerString,proto3" json:"inner_string,omitempty"`
	InnerInt           int32     `protobuf:"varint,2,opt,name=inner_int,json=innerInt,proto3" json:"inner_int,omitempty"`
	InnerBool          bool      `protobuf:"varint,3,opt,name=inner_bool,json=innerBool,proto3" json:"inner_bool,omitempty"`
	InnerRepeatedFloat []float32 `protobuf:"fixed32,4,rep,packed,name=inner_repeated_float,json=innerRepeatedFloat,proto3" json:"inner_repeated_float,omitempty"`
}

func (x *Inner) Reset() {
	*x = Inner{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testdata_test_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Inner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Inner) ProtoMessage() {}

func (x *Inner) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_test_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Inner.ProtoReflect.Descriptor instead.
func (*Inner) Descriptor() ([]byte, []int) {
	return file_testdata_test_proto_rawDescGZIP(), []int{1}
}

func (x *Inner) GetInnerString() string {
	if x != nil {
		return x.InnerString
	}
	return ""
}

func (x *Inner) GetInnerInt() int32 {
	if x != nil {
		return x.InnerInt
	}
	return 0
}

func (x *Inner) GetInnerBool() bool {
	if x != nil {
		return x.InnerBool
	}
	return false
}

func (x *Inner) GetInnerRepeatedFloat() []float32 {
	if x != nil {
		return x.InnerRepeatedFloat
	}
	return nil
}

type BigInt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BigintUint64   uint64 `protobuf:"varint,1,opt,name=bigint_uint64,json=bigintUint64,proto3" json:"bigint_uint64,omitempty"`
	BigintInt64    int64  `protobuf:"varint,2,opt,name=bigint_int64,json=bigintInt64,proto3" json:"bigint_int64,omitempty"`
	BigintSint64   int64  `protobuf:"zigzag64,3,opt,name=bigint_sint64,json=bigintSint64,proto3" json:"bigint_sint64,omitempty"`
	BigintFixed64  uint64 `protobuf:"fixed64,4,opt,name=bigint_fixed64,json=bigintFixed64,proto3" json:"bigint_fixed64,omitempty"`
	BigintSfixed64 int64  `protobuf:"fixed64,5,opt,name=bigint_sfixed64,json=bigintSfixed64,proto3" json:"bigint_sfixed64,omitempty"`
}

func (x *BigInt) Reset() {
	*x = BigInt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testdata_test_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BigInt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BigInt) ProtoMessage() {}

func (x *BigInt) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_test_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BigInt.ProtoReflect.Descriptor instead.
func (*BigInt) Descriptor() ([]byte, []int) {
	return file_testdata_test_proto_rawDescGZIP(), []int{2}
}

func (x *BigInt) GetBigintUint64() uint64 {
	if x != nil {
		return x.BigintUint64
	}
	return 0
}

func (x *BigInt) GetBigintInt64() int64 {
	if x != nil {
		return x.BigintInt64
	}
	return 0
}

func (x *BigInt) GetBigintSint64() int64 {
	if x != nil {
		return x.BigintSint64
	}
	return 0
}

func (x *BigInt) GetBigintFixed64() uint64 {
	if x != nil {
		return x.BigintFixed64
	}
	return 0
}

func (x *BigInt) GetBigintSfixed64() int64 {
	if x != nil {
		return x.BigintSfixed64
	}
	return 0
}

var File_testdata_test_proto protoreflect.FileDescriptor

var file_testdata_test_proto_rawDesc = []byte{
	0x0a, 0x13, 0x74, 0x65, 0x73, 0x74, 0x64, 0x61, 0x74, 0x61, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x74, 0x65, 0x73, 0x74, 0x22, 0x73, 0x0a, 0x05, 0x4f,
	0x75, 0x74, 0x65, 0x72, 0x12, 0x21, 0x0a, 0x0c, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x5f, 0x73, 0x74,
	0x72, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6f, 0x75, 0x74, 0x65,
	0x72, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x21, 0x0a, 0x05, 0x69, 0x6e, 0x6e, 0x65, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x49, 0x6e,
	0x6e, 0x65, 0x72, 0x52, 0x05, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x12, 0x24, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x74, 0x65, 0x73,
	0x74, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x22, 0x98, 0x01, 0x0a, 0x05, 0x49, 0x6e, 0x6e, 0x65, 0x72, 0x12, 0x21, 0x0a, 0x0c, 0x69, 0x6e,
	0x6e, 0x65, 0x72, 0x5f, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x1b, 0x0a,
	0x09, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x5f, 0x69, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x08, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x49, 0x6e, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x6e,
	0x6e, 0x65, 0x72, 0x5f, 0x62, 0x6f, 0x6f, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09,
	0x69, 0x6e, 0x6e, 0x65, 0x72, 0x42, 0x6f, 0x6f, 0x6c, 0x12, 0x30, 0x0a, 0x14, 0x69, 0x6e, 0x6e,
	0x65, 0x72, 0x5f, 0x72, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x66, 0x6c, 0x6f, 0x61,
	0x74, 0x18, 0x04, 0x20, 0x03, 0x28, 0x02, 0x52, 0x12, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x52, 0x65,
	0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x22, 0xc5, 0x01, 0x0a, 0x06,
	0x42, 0x69, 0x67, 0x49, 0x6e, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x62, 0x69, 0x67, 0x69, 0x6e, 0x74,
	0x5f, 0x75, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0c, 0x62,
	0x69, 0x67, 0x69, 0x6e, 0x74, 0x55, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x12, 0x21, 0x0a, 0x0c, 0x62,
	0x69, 0x67, 0x69, 0x6e, 0x74, 0x5f, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0b, 0x62, 0x69, 0x67, 0x69, 0x6e, 0x74, 0x49, 0x6e, 0x74, 0x36, 0x34, 0x12, 0x23,
	0x0a, 0x0d, 0x62, 0x69, 0x67, 0x69, 0x6e, 0x74, 0x5f, 0x73, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x12, 0x52, 0x0c, 0x62, 0x69, 0x67, 0x69, 0x6e, 0x74, 0x53, 0x69, 0x6e,
	0x74, 0x36, 0x34, 0x12, 0x25, 0x0a, 0x0e, 0x62, 0x69, 0x67, 0x69, 0x6e, 0x74, 0x5f, 0x66, 0x69,
	0x78, 0x65, 0x64, 0x36, 0x34, 0x18, 0x04, 0x20, 0x01, 0x28, 0x06, 0x52, 0x0d, 0x62, 0x69, 0x67,
	0x69, 0x6e, 0x74, 0x46, 0x69, 0x78, 0x65, 0x64, 0x36, 0x34, 0x12, 0x27, 0x0a, 0x0f, 0x62, 0x69,
	0x67, 0x69, 0x6e, 0x74, 0x5f, 0x73, 0x66, 0x69, 0x78, 0x65, 0x64, 0x36, 0x34, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x10, 0x52, 0x0e, 0x62, 0x69, 0x67, 0x69, 0x6e, 0x74, 0x53, 0x66, 0x69, 0x78, 0x65,
	0x64, 0x36, 0x34, 0x2a, 0x44, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x0a,
	0x0e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x10,
	0x00, 0x12, 0x12, 0x0a, 0x0e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x53, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x10, 0x01, 0x12, 0x12, 0x0a, 0x0e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f,
	0x46, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x10, 0x02, 0x42, 0x0f, 0x5a, 0x0d, 0x74, 0x65, 0x73,
	0x74, 0x64, 0x61, 0x74, 0x61, 0x3b, 0x74, 0x65, 0x73, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_testdata_test_proto_rawDescOnce sync.Once
	file_testdata_test_proto_rawDescData = file_testdata_test_proto_rawDesc
)

func file_testdata_test_proto_rawDescGZIP() []byte {
	file_testdata_test_proto_rawDescOnce.Do(func() {
		file_testdata_test_proto_rawDescData = protoimpl.X.CompressGZIP(file_testdata_test_proto_rawDescData)
	})
	return file_testdata_test_proto_rawDescData
}

var file_testdata_test_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_testdata_test_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_testdata_test_proto_goTypes = []interface{}{
	(Status)(0),    // 0: test.Status
	(*Outer)(nil),  // 1: test.Outer
	(*Inner)(nil),  // 2: test.Inner
	(*BigInt)(nil), // 3: test.BigInt
}
var file_testdata_test_proto_depIdxs = []int32{
	2, // 0: test.Outer.inner:type_name -> test.Inner
	0, // 1: test.Outer.status:type_name -> test.Status
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_testdata_test_proto_init() }
func file_testdata_test_proto_init() {
	if File_testdata_test_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_testdata_test_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Outer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_testdata_test_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Inner); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_testdata_test_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BigInt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_testdata_test_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_testdata_test_proto_goTypes,
		DependencyIndexes: file_testdata_test_proto_depIdxs,
		EnumInfos:         file_testdata_test_proto_enumTypes,
		MessageInfos:      file_testdata_test_proto_msgTypes,
	}.Build()
	File_testdata_test_proto = out.File
	file_testdata_test_proto_rawDesc = nil
	file_testdata_test_proto_goTypes = nil
	file_testdata_test_proto_depIdxs = nil
}
