#!/bin/bash
cd .. && go build . && mv protoc-gen-gin-bff ~/go/bin/
protoc -I=. --go_out=paths=source_relative:./pb/ --gin-bff_out=paths=source_relative:./pb/ \
--proto_path=./testdata/proto testdata/proto/test.proto


